//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.16 at 11:26:56 AM MEZ 
//


package de.uop.dimis.air.internalObjects.jpsearch;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for ExternalDescriptonType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExternalDescriptonType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TagName">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="fromNamespace" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                 &lt;attribute name="fromNamespacePrefix" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;choice>
 *           &lt;element name="LiteralValue">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;attribute name="fromControlledVocabularyOfLiterals" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                   &lt;attribute name="fromGrammarOfLiterals" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="ResourceValue">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;attribute name="fromNamespace" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="StructuredValue">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;any/>
 *                   &lt;/sequence>
 *                   &lt;attribute name="fromNamespace" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExternalDescriptonType", propOrder = {
    "tagName",
    "literalValue",
    "resourceValue",
    "structuredValue"
})
public class ExternalDescriptonType {

    @XmlElement(name = "TagName", required = true)
    protected ExternalDescriptonType.TagName tagName;
    @XmlElement(name = "LiteralValue")
    protected ExternalDescriptonType.LiteralValue literalValue;
    @XmlElement(name = "ResourceValue")
    protected ExternalDescriptonType.ResourceValue resourceValue;
    @XmlElement(name = "StructuredValue")
    protected ExternalDescriptonType.StructuredValue structuredValue;

    /**
     * Gets the value of the tagName property.
     * 
     * @return
     *     possible object is
     *     {@link ExternalDescriptonType.TagName }
     *     
     */
    public ExternalDescriptonType.TagName getTagName() {
        return tagName;
    }

    /**
     * Sets the value of the tagName property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExternalDescriptonType.TagName }
     *     
     */
    public void setTagName(ExternalDescriptonType.TagName value) {
        this.tagName = value;
    }

    /**
     * Gets the value of the literalValue property.
     * 
     * @return
     *     possible object is
     *     {@link ExternalDescriptonType.LiteralValue }
     *     
     */
    public ExternalDescriptonType.LiteralValue getLiteralValue() {
        return literalValue;
    }

    /**
     * Sets the value of the literalValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExternalDescriptonType.LiteralValue }
     *     
     */
    public void setLiteralValue(ExternalDescriptonType.LiteralValue value) {
        this.literalValue = value;
    }

    /**
     * Gets the value of the resourceValue property.
     * 
     * @return
     *     possible object is
     *     {@link ExternalDescriptonType.ResourceValue }
     *     
     */
    public ExternalDescriptonType.ResourceValue getResourceValue() {
        return resourceValue;
    }

    /**
     * Sets the value of the resourceValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExternalDescriptonType.ResourceValue }
     *     
     */
    public void setResourceValue(ExternalDescriptonType.ResourceValue value) {
        this.resourceValue = value;
    }

    /**
     * Gets the value of the structuredValue property.
     * 
     * @return
     *     possible object is
     *     {@link ExternalDescriptonType.StructuredValue }
     *     
     */
    public ExternalDescriptonType.StructuredValue getStructuredValue() {
        return structuredValue;
    }

    /**
     * Sets the value of the structuredValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExternalDescriptonType.StructuredValue }
     *     
     */
    public void setStructuredValue(ExternalDescriptonType.StructuredValue value) {
        this.structuredValue = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="fromControlledVocabularyOfLiterals" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *       &lt;attribute name="fromGrammarOfLiterals" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "content"
    })
    public static class LiteralValue {

        @XmlValue
        protected String content;
        @XmlAttribute
        @XmlSchemaType(name = "anyURI")
        protected String fromControlledVocabularyOfLiterals;
        @XmlAttribute
        @XmlSchemaType(name = "anyURI")
        protected String fromGrammarOfLiterals;

        /**
         * Gets the value of the content property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContent() {
            return content;
        }

        /**
         * Sets the value of the content property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContent(String value) {
            this.content = value;
        }

        /**
         * Gets the value of the fromControlledVocabularyOfLiterals property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFromControlledVocabularyOfLiterals() {
            return fromControlledVocabularyOfLiterals;
        }

        /**
         * Sets the value of the fromControlledVocabularyOfLiterals property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFromControlledVocabularyOfLiterals(String value) {
            this.fromControlledVocabularyOfLiterals = value;
        }

        /**
         * Gets the value of the fromGrammarOfLiterals property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFromGrammarOfLiterals() {
            return fromGrammarOfLiterals;
        }

        /**
         * Sets the value of the fromGrammarOfLiterals property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFromGrammarOfLiterals(String value) {
            this.fromGrammarOfLiterals = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="fromNamespace" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "content"
    })
    public static class ResourceValue {

        @XmlValue
        protected String content;
        @XmlAttribute
        @XmlSchemaType(name = "anyURI")
        protected String fromNamespace;

        /**
         * Gets the value of the content property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContent() {
            return content;
        }

        /**
         * Sets the value of the content property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContent(String value) {
            this.content = value;
        }

        /**
         * Gets the value of the fromNamespace property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFromNamespace() {
            return fromNamespace;
        }

        /**
         * Sets the value of the fromNamespace property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFromNamespace(String value) {
            this.fromNamespace = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;any/>
     *       &lt;/sequence>
     *       &lt;attribute name="fromNamespace" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "content"
    })
    public static class StructuredValue {

        @XmlMixed
        @XmlAnyElement(lax = true)
        protected List<Object> content;
        @XmlAttribute(required = true)
        @XmlSchemaType(name = "anyURI")
        protected String fromNamespace;

        /**
         * Gets the value of the content property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the content property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getContent().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Object }
         * {@link String }
         * 
         * 
         */
        public List<Object> getContent() {
            if (content == null) {
                content = new ArrayList<Object>();
            }
            return this.content;
        }

        /**
         * Gets the value of the fromNamespace property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFromNamespace() {
            return fromNamespace;
        }

        /**
         * Sets the value of the fromNamespace property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFromNamespace(String value) {
            this.fromNamespace = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="fromNamespace" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *       &lt;attribute name="fromNamespacePrefix" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "content"
    })
    public static class TagName {

        @XmlValue
        protected String content;
        @XmlAttribute
        @XmlSchemaType(name = "anyURI")
        protected String fromNamespace;
        @XmlAttribute
        protected String fromNamespacePrefix;

        /**
         * Gets the value of the content property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContent() {
            return content;
        }

        /**
         * Sets the value of the content property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContent(String value) {
            this.content = value;
        }

        /**
         * Gets the value of the fromNamespace property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFromNamespace() {
            return fromNamespace;
        }

        /**
         * Sets the value of the fromNamespace property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFromNamespace(String value) {
            this.fromNamespace = value;
        }

        /**
         * Gets the value of the fromNamespacePrefix property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFromNamespacePrefix() {
            return fromNamespacePrefix;
        }

        /**
         * Sets the value of the fromNamespacePrefix property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFromNamespacePrefix(String value) {
            this.fromNamespacePrefix = value;
        }

    }

}
