//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.16 at 11:26:56 AM MEZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "JPSearch:schema:coremetadata", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.uop.dimis.air.internalObjects.jpsearch;
