//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.16 at 11:26:56 AM MEZ 
//


package de.uop.dimis.air.internalObjects.jpsearch;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PublisherType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PublisherType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="PersonName" type="{JPSearch:schema:coremetadata}PersonNameType"/>
 *           &lt;element name="OrganizationInformation" type="{JPSearch:schema:coremetadata}OrganizationType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PublisherType", propOrder = {
    "personNameOrOrganizationInformation"
})
public class PublisherType {

    @XmlElements({
        @XmlElement(name = "OrganizationInformation", type = OrganizationType.class),
        @XmlElement(name = "PersonName", type = PersonNameType.class)
    })
    protected List<Object> personNameOrOrganizationInformation;

    /**
     * Gets the value of the personNameOrOrganizationInformation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the personNameOrOrganizationInformation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPersonNameOrOrganizationInformation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrganizationType }
     * {@link PersonNameType }
     * 
     * 
     */
    public List<Object> getPersonNameOrOrganizationInformation() {
        if (personNameOrOrganizationInformation == null) {
            personNameOrOrganizationInformation = new ArrayList<Object>();
        }
        return this.personNameOrOrganizationInformation;
    }

}
