//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.16 at 11:26:56 AM MEZ 
//


package de.uop.dimis.air.internalObjects.jpsearch;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RightsDescriptionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RightsDescriptionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RightsDescriptionInformation" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ActualRightsDescriptionReference" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="ActualRightsDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RightsDescriptionType", propOrder = {
    "rightsDescriptionInformation",
    "description",
    "actualRightsDescriptionReference",
    "actualRightsDescription"
})
public class RightsDescriptionType {

    @XmlElement(name = "RightsDescriptionInformation", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String rightsDescriptionInformation;
    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "ActualRightsDescriptionReference", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String actualRightsDescriptionReference;
    @XmlElement(name = "ActualRightsDescription")
    protected String actualRightsDescription;

    /**
     * Gets the value of the rightsDescriptionInformation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRightsDescriptionInformation() {
        return rightsDescriptionInformation;
    }

    /**
     * Sets the value of the rightsDescriptionInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRightsDescriptionInformation(String value) {
        this.rightsDescriptionInformation = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the actualRightsDescriptionReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActualRightsDescriptionReference() {
        return actualRightsDescriptionReference;
    }

    /**
     * Sets the value of the actualRightsDescriptionReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActualRightsDescriptionReference(String value) {
        this.actualRightsDescriptionReference = value;
    }

    /**
     * Gets the value of the actualRightsDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActualRightsDescription() {
        return actualRightsDescription;
    }

    /**
     * Sets the value of the actualRightsDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActualRightsDescription(String value) {
        this.actualRightsDescription = value;
    }

}
