//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.16 at 11:26:56 AM MEZ 
//


package de.uop.dimis.air.internalObjects.jpsearch;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SourceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SourceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SourceElementType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SourceElement" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="SourceElementTitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="SourceElementDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="SourceElementIdentifier" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="CreationMethod" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CreationDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SourceType", propOrder = {
    "sourceElementType",
    "sourceElement",
    "creationMethod",
    "creationDescription"
})
public class SourceType {

    @XmlElement(name = "SourceElementType", required = true)
    protected String sourceElementType;
    @XmlElement(name = "SourceElement", required = true)
    protected List<SourceType.SourceElement> sourceElement;
    @XmlElement(name = "CreationMethod", required = true)
    protected String creationMethod;
    @XmlElement(name = "CreationDescription", required = true)
    protected String creationDescription;

    /**
     * Gets the value of the sourceElementType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceElementType() {
        return sourceElementType;
    }

    /**
     * Sets the value of the sourceElementType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceElementType(String value) {
        this.sourceElementType = value;
    }

    /**
     * Gets the value of the sourceElement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sourceElement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSourceElement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SourceType.SourceElement }
     * 
     * 
     */
    public List<SourceType.SourceElement> getSourceElement() {
        if (sourceElement == null) {
            sourceElement = new ArrayList<SourceType.SourceElement>();
        }
        return this.sourceElement;
    }

    /**
     * Gets the value of the creationMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreationMethod() {
        return creationMethod;
    }

    /**
     * Sets the value of the creationMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreationMethod(String value) {
        this.creationMethod = value;
    }

    /**
     * Gets the value of the creationDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreationDescription() {
        return creationDescription;
    }

    /**
     * Sets the value of the creationDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreationDescription(String value) {
        this.creationDescription = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="SourceElementTitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="SourceElementDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="SourceElementIdentifier" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "sourceElementTitle",
        "sourceElementDescription",
        "sourceElementIdentifier"
    })
    public static class SourceElement {

        @XmlElement(name = "SourceElementTitle", required = true)
        protected String sourceElementTitle;
        @XmlElement(name = "SourceElementDescription", required = true)
        protected String sourceElementDescription;
        @XmlElement(name = "SourceElementIdentifier")
        @XmlSchemaType(name = "anyURI")
        protected String sourceElementIdentifier;

        /**
         * Gets the value of the sourceElementTitle property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSourceElementTitle() {
            return sourceElementTitle;
        }

        /**
         * Sets the value of the sourceElementTitle property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSourceElementTitle(String value) {
            this.sourceElementTitle = value;
        }

        /**
         * Gets the value of the sourceElementDescription property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSourceElementDescription() {
            return sourceElementDescription;
        }

        /**
         * Sets the value of the sourceElementDescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSourceElementDescription(String value) {
            this.sourceElementDescription = value;
        }

        /**
         * Gets the value of the sourceElementIdentifier property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSourceElementIdentifier() {
            return sourceElementIdentifier;
        }

        /**
         * Sets the value of the sourceElementIdentifier property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSourceElementIdentifier(String value) {
            this.sourceElementIdentifier = value;
        }

    }

}
