//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.22 at 12:10:03 PM MESZ 
//


package de.uop.dimis.air.internalObjects.dicomQuery;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.uop.dimis.air.internalObjects.dicomQuery package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Dicom_QNAME = new QName("urn:medico:dicom:schema:2011", "Dicom");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.uop.dimis.air.internalObjects.dicomQuery
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DicomCondition }
     * 
     */
    public DicomCondition createDicomCondition() {
        return new DicomCondition();
    }

    /**
     * Create an instance of {@link DicomRootType }
     * 
     */
    public DicomRootType createDicomRootType() {
        return new DicomRootType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DicomRootType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:medico:dicom:schema:2011", name = "Dicom")
    public JAXBElement<DicomRootType> createDicom(DicomRootType value) {
        return new JAXBElement<DicomRootType>(_Dicom_QNAME, DicomRootType.class, null, value);
    }

}
