//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.14 at 10:50:29 AM CEST 
//


package de.uop.dimis.air.internalObjects.mpqf;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LowerCase complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LowerCase">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:mpeg:mpqf:schema:2008}StringExpressionType">
 *       &lt;sequence>
 *         &lt;group ref="{urn:mpeg:mpqf:schema:2008}StringOperands"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LowerCase", propOrder = {
    "stringValue",
    "stringField",
    "stringExpression",
    "semanticStringField"
})
public class LowerCase
    extends StringExpressionType
{

    @XmlElement(name = "StringValue", namespace = "urn:mpeg:mpqf:schema:2008")
    protected String stringValue;
    @XmlElement(name = "StringField", namespace = "urn:mpeg:mpqf:schema:2008")
    protected FieldType stringField;
    @XmlElement(name = "StringExpression", namespace = "urn:mpeg:mpqf:schema:2008")
    protected StringExpressionType stringExpression;
    @XmlElement(name = "SemanticStringField", namespace = "urn:mpeg:mpqf:schema:2008")
    protected SemanticFieldType semanticStringField;

    /**
     * Gets the value of the stringValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStringValue() {
        return stringValue;
    }

    /**
     * Sets the value of the stringValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStringValue(String value) {
        this.stringValue = value;
    }

    /**
     * Gets the value of the stringField property.
     * 
     * @return
     *     possible object is
     *     {@link FieldType }
     *     
     */
    public FieldType getStringField() {
        return stringField;
    }

    /**
     * Sets the value of the stringField property.
     * 
     * @param value
     *     allowed object is
     *     {@link FieldType }
     *     
     */
    public void setStringField(FieldType value) {
        this.stringField = value;
    }

    /**
     * Gets the value of the stringExpression property.
     * 
     * @return
     *     possible object is
     *     {@link StringExpressionType }
     *     
     */
    public StringExpressionType getStringExpression() {
        return stringExpression;
    }

    /**
     * Sets the value of the stringExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringExpressionType }
     *     
     */
    public void setStringExpression(StringExpressionType value) {
        this.stringExpression = value;
    }

    /**
     * Gets the value of the semanticStringField property.
     * 
     * @return
     *     possible object is
     *     {@link SemanticFieldType }
     *     
     */
    public SemanticFieldType getSemanticStringField() {
        return semanticStringField;
    }

    /**
     * Sets the value of the semanticStringField property.
     * 
     * @param value
     *     allowed object is
     *     {@link SemanticFieldType }
     *     
     */
    public void setSemanticStringField(SemanticFieldType value) {
        this.semanticStringField = value;
    }

}
