//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.14 at 10:50:29 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:mpeg:mpqf:schema:2008")
package de.uop.dimis.air.internalObjects.mpqf;
