//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.14 at 10:50:29 AM CEST 
//


package de.uop.dimis.air.internalObjects.mpqf;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for XOR complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="XOR">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:mpeg:mpqf:schema:2008}BooleanExpressionType">
 *       &lt;sequence>
 *         &lt;element name="Condition" type="{urn:mpeg:mpqf:schema:2008}BooleanExpressionType" maxOccurs="2" minOccurs="2"/>
 *       &lt;/sequence>
 *       &lt;attribute name="scoringFunction" type="{urn:mpeg:mpqf:schema:2008}SimpleTermType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XOR", propOrder = {
    "condition"
})
public class XOR
    extends BooleanExpressionType
{

    @XmlElement(name = "Condition", namespace = "urn:mpeg:mpqf:schema:2008", required = true)
    protected List<BooleanExpressionType> condition;
    @XmlAttribute
    protected String scoringFunction;

    /**
     * Gets the value of the condition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the condition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCondition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BooleanExpressionType }
     * 
     * 
     */
    public List<BooleanExpressionType> getCondition() {
        if (condition == null) {
            condition = new ArrayList<BooleanExpressionType>();
        }
        return this.condition;
    }

    /**
     * Gets the value of the scoringFunction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScoringFunction() {
        return scoringFunction;
    }

    /**
     * Sets the value of the scoringFunction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScoringFunction(String value) {
        this.scoringFunction = value;
    }

}
