//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.16 at 11:26:56 AM MEZ 
//


package de.uop.dimis.air.internalObjects.jpsearch;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ControlledRatingTermType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ControlledRatingTermType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LabelDefinition" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="LabelValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ControlledRatingTermType", propOrder = {
    "labelDefinition",
    "labelValue"
})
public class ControlledRatingTermType {

    @XmlElement(name = "LabelDefinition", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String labelDefinition;
    @XmlElement(name = "LabelValue", required = true)
    protected String labelValue;

    /**
     * Gets the value of the labelDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabelDefinition() {
        return labelDefinition;
    }

    /**
     * Sets the value of the labelDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabelDefinition(String value) {
        this.labelDefinition = value;
    }

    /**
     * Gets the value of the labelValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabelValue() {
        return labelValue;
    }

    /**
     * Sets the value of the labelValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabelValue(String value) {
        this.labelValue = value;
    }

}
