//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.16 at 11:26:56 AM MEZ 
//


package de.uop.dimis.air.internalObjects.jpsearch;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RegionOfInterestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RegionOfInterestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RegionLocator" type="{JPSearch:schema:coremetadata}RegionLocatorType"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Keyword" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ContentDescription" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Person" type="{JPSearch:schema:coremetadata}PersonType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="Object" type="{JPSearch:schema:coremetadata}ObjectType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="Place" type="{JPSearch:schema:coremetadata}PlaceType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="Event" type="{JPSearch:schema:coremetadata}EventType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ExternalDescription" type="{JPSearch:schema:coremetadata}ExternalDescriptonType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RegionOfInterestType", propOrder = {
    "regionLocator",
    "description",
    "keyword",
    "title",
    "contentDescription",
    "externalDescription"
})
public class RegionOfInterestType {

    @XmlElement(name = "RegionLocator", required = true)
    protected RegionLocatorType regionLocator;
    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "Keyword")
    protected List<String> keyword;
    @XmlElement(name = "Title")
    protected String title;
    @XmlElement(name = "ContentDescription")
    protected RegionOfInterestType.ContentDescription contentDescription;
    @XmlElement(name = "ExternalDescription")
    protected List<ExternalDescriptonType> externalDescription;

    /**
     * Gets the value of the regionLocator property.
     * 
     * @return
     *     possible object is
     *     {@link RegionLocatorType }
     *     
     */
    public RegionLocatorType getRegionLocator() {
        return regionLocator;
    }

    /**
     * Sets the value of the regionLocator property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegionLocatorType }
     *     
     */
    public void setRegionLocator(RegionLocatorType value) {
        this.regionLocator = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the keyword property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the keyword property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKeyword().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getKeyword() {
        if (keyword == null) {
            keyword = new ArrayList<String>();
        }
        return this.keyword;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the contentDescription property.
     * 
     * @return
     *     possible object is
     *     {@link RegionOfInterestType.ContentDescription }
     *     
     */
    public RegionOfInterestType.ContentDescription getContentDescription() {
        return contentDescription;
    }

    /**
     * Sets the value of the contentDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegionOfInterestType.ContentDescription }
     *     
     */
    public void setContentDescription(RegionOfInterestType.ContentDescription value) {
        this.contentDescription = value;
    }

    /**
     * Gets the value of the externalDescription property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the externalDescription property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExternalDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExternalDescriptonType }
     * 
     * 
     */
    public List<ExternalDescriptonType> getExternalDescription() {
        if (externalDescription == null) {
            externalDescription = new ArrayList<ExternalDescriptonType>();
        }
        return this.externalDescription;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Person" type="{JPSearch:schema:coremetadata}PersonType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="Object" type="{JPSearch:schema:coremetadata}ObjectType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="Place" type="{JPSearch:schema:coremetadata}PlaceType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="Event" type="{JPSearch:schema:coremetadata}EventType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "person",
        "object",
        "place",
        "event"
    })
    public static class ContentDescription {

        @XmlElement(name = "Person")
        protected List<PersonType> person;
        @XmlElement(name = "Object")
        protected List<ObjectType> object;
        @XmlElement(name = "Place")
        protected List<PlaceType> place;
        @XmlElement(name = "Event")
        protected List<EventType> event;

        /**
         * Gets the value of the person property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the person property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPerson().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PersonType }
         * 
         * 
         */
        public List<PersonType> getPerson() {
            if (person == null) {
                person = new ArrayList<PersonType>();
            }
            return this.person;
        }

        /**
         * Gets the value of the object property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the object property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getObject().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ObjectType }
         * 
         * 
         */
        public List<ObjectType> getObject() {
            if (object == null) {
                object = new ArrayList<ObjectType>();
            }
            return this.object;
        }

        /**
         * Gets the value of the place property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the place property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPlace().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PlaceType }
         * 
         * 
         */
        public List<PlaceType> getPlace() {
            if (place == null) {
                place = new ArrayList<PlaceType>();
            }
            return this.place;
        }

        /**
         * Gets the value of the event property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the event property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEvent().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EventType }
         * 
         * 
         */
        public List<EventType> getEvent() {
            if (event == null) {
                event = new ArrayList<EventType>();
            }
            return this.event;
        }

    }

}
