//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.14 at 10:50:29 AM CEST 
//


package de.uop.dimis.air.internalObjects.mpqf;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Abs complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Abs">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:mpeg:mpqf:schema:2008}ArithmeticExpressionType">
 *       &lt;sequence>
 *         &lt;group ref="{urn:mpeg:mpqf:schema:2008}ArithmeticOperands"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Abs", propOrder = {
    "doubleValue",
    "longValue",
    "arithmeticField",
    "arithmeticExpression",
    "semanticArithmeticField"
})
public class Abs
    extends ArithmeticExpressionType
{

    @XmlElement(name = "DoubleValue", namespace = "urn:mpeg:mpqf:schema:2008")
    protected Double doubleValue;
    @XmlElement(name = "LongValue", namespace = "urn:mpeg:mpqf:schema:2008")
    protected Long longValue;
    @XmlElement(name = "ArithmeticField", namespace = "urn:mpeg:mpqf:schema:2008")
    protected FieldType arithmeticField;
    @XmlElement(name = "ArithmeticExpression", namespace = "urn:mpeg:mpqf:schema:2008")
    protected ArithmeticExpressionType arithmeticExpression;
    @XmlElement(name = "SemanticArithmeticField", namespace = "urn:mpeg:mpqf:schema:2008")
    protected SemanticFieldType semanticArithmeticField;

    /**
     * Gets the value of the doubleValue property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getDoubleValue() {
        return doubleValue;
    }

    /**
     * Sets the value of the doubleValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setDoubleValue(Double value) {
        this.doubleValue = value;
    }

    /**
     * Gets the value of the longValue property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getLongValue() {
        return longValue;
    }

    /**
     * Sets the value of the longValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setLongValue(Long value) {
        this.longValue = value;
    }

    /**
     * Gets the value of the arithmeticField property.
     * 
     * @return
     *     possible object is
     *     {@link FieldType }
     *     
     */
    public FieldType getArithmeticField() {
        return arithmeticField;
    }

    /**
     * Sets the value of the arithmeticField property.
     * 
     * @param value
     *     allowed object is
     *     {@link FieldType }
     *     
     */
    public void setArithmeticField(FieldType value) {
        this.arithmeticField = value;
    }

    /**
     * Gets the value of the arithmeticExpression property.
     * 
     * @return
     *     possible object is
     *     {@link ArithmeticExpressionType }
     *     
     */
    public ArithmeticExpressionType getArithmeticExpression() {
        return arithmeticExpression;
    }

    /**
     * Sets the value of the arithmeticExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArithmeticExpressionType }
     *     
     */
    public void setArithmeticExpression(ArithmeticExpressionType value) {
        this.arithmeticExpression = value;
    }

    /**
     * Gets the value of the semanticArithmeticField property.
     * 
     * @return
     *     possible object is
     *     {@link SemanticFieldType }
     *     
     */
    public SemanticFieldType getSemanticArithmeticField() {
        return semanticArithmeticField;
    }

    /**
     * Sets the value of the semanticArithmeticField property.
     * 
     * @param value
     *     allowed object is
     *     {@link SemanticFieldType }
     *     
     */
    public void setSemanticArithmeticField(SemanticFieldType value) {
        this.semanticArithmeticField = value;
    }

}
