//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.14 at 10:50:29 AM CEST 
//


package de.uop.dimis.air.internalObjects.mpqf;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MediaLocatorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MediaLocatorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="MediaUri" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *           &lt;element name="InlineMedia" type="{urn:mpeg:mpqf:schema:2008}InlineMediaType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MediaLocatorType", propOrder = {
    "mediaUri",
    "inlineMedia"
})
public class MediaLocatorType {

    @XmlElement(name = "MediaUri", namespace = "urn:mpeg:mpqf:schema:2008")
    protected String mediaUri;
    @XmlElement(name = "InlineMedia", namespace = "urn:mpeg:mpqf:schema:2008")
    protected InlineMediaType inlineMedia;

    /**
     * Gets the value of the mediaUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMediaUri() {
        return mediaUri;
    }

    /**
     * Sets the value of the mediaUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMediaUri(String value) {
        this.mediaUri = value;
    }

    /**
     * Gets the value of the inlineMedia property.
     * 
     * @return
     *     possible object is
     *     {@link InlineMediaType }
     *     
     */
    public InlineMediaType getInlineMedia() {
        return inlineMedia;
    }

    /**
     * Sets the value of the inlineMedia property.
     * 
     * @param value
     *     allowed object is
     *     {@link InlineMediaType }
     *     
     */
    public void setInlineMedia(InlineMediaType value) {
        this.inlineMedia = value;
    }

}
