//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.14 at 10:50:29 AM CEST 
//


package de.uop.dimis.air.internalObjects.mpqf;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SortByFieldType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SortByFieldType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:mpeg:mpqf:schema:2008}AbstractSortByType">
 *       &lt;choice>
 *         &lt;element name="Field" type="{urn:mpeg:mpqf:schema:2008}FieldType"/>
 *         &lt;element name="SemanticField" type="{urn:mpeg:mpqf:schema:2008}SemanticFieldType"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SortByFieldType", propOrder = {
    "field",
    "semanticField"
})
public class SortByFieldType
    extends AbstractSortByType
{

    @XmlElement(name = "Field", namespace = "urn:mpeg:mpqf:schema:2008")
    protected FieldType field;
    @XmlElement(name = "SemanticField", namespace = "urn:mpeg:mpqf:schema:2008")
    protected SemanticFieldType semanticField;

    /**
     * Gets the value of the field property.
     * 
     * @return
     *     possible object is
     *     {@link FieldType }
     *     
     */
    public FieldType getField() {
        return field;
    }

    /**
     * Sets the value of the field property.
     * 
     * @param value
     *     allowed object is
     *     {@link FieldType }
     *     
     */
    public void setField(FieldType value) {
        this.field = value;
    }

    /**
     * Gets the value of the semanticField property.
     * 
     * @return
     *     possible object is
     *     {@link SemanticFieldType }
     *     
     */
    public SemanticFieldType getSemanticField() {
        return semanticField;
    }

    /**
     * Sets the value of the semanticField property.
     * 
     * @param value
     *     allowed object is
     *     {@link SemanticFieldType }
     *     
     */
    public void setSemanticField(SemanticFieldType value) {
        this.semanticField = value;
    }

}
